#!/bin/bash
. "$(dirname -- "${0}")/_/husky.sh"

# Rodar o phpstan
if ! ./vendor/bin/phpstan; then
    echo "Opa! Deu ruim aqui com PHPSTAN. Arrume antes de continuar... 😉";
    exit 1;
fi;

# Rodar os testes
if ! php artisan test --parallel | php; then
    echo "Opa! Deu ruim aqui com algum teste. Arrume antes de continuar... 😉";
    exit 1;
fi;

# Formatar cada arquivo alterado usando o Laravel Pint
STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep -E "\.php$|\.php1$" || true);

for FILE in $STAGED_FILES; do
    ./vendor/bin/pint "${FILE}" > /dev/null 2>&1
    git add "${FILE}"
done

exit 0;
